const term = (parts: string[]): string => parts.join('');
const phrase = (...parts: string[]): string => parts.join(' ');

export const forbiddenPublicArtifactTerms = [
  term(['da', 'vid']),
  term(['me', 'dici']),
  term(['pro', 'tein']),
  term(['e', 'pg']),
  term(['epo', 'gee']),
  phrase(term(['pe', 'ter']), term(['ra', 'hal'])),
  phrase(term(['ju', 'lia']), term(['fo', 'x'])),
  term(['shop', 'ify']),
  'amazon',
  'walmart',
  'target',
  'costco',
  'tiktok',
  'instagram',
  'twitter',
  'x.com',
  'linkedin',
  'stripe',
  'auth0',
  'openai',
  'anthropic',
  'gemini',
  'slack',
  'jira',
  'zendesk',
  'salesforce',
  'http://',
  'https://',
  'www.',
  term(['check', 'out']),
  term(['ca', 'rt']),
  term(['or', 'der']),
  term(['pay', 'ment']),
  term(['cus', 'tomer']),
  term(['mer', 'chant']),
  term(['store', 'front']),
  term(['p', 'dp']),
  term(['au', 'th']),
  term(['ac', 'count']),
  term(['cre', 'dential']),
  term(['tele', 'gram']),
  term(['her', 'mes']),
  term(['u', 'cp']),
  term(['m', 'cp']),
  term(['a', 'cp']),
  term(['com', 'merce']),
  term(['tick', 'et']),
  term(['inci', 'dent']),
  'endpoint',
  'api/',
  'founder',
  'ceo',
  phrase(term(['pri', 'vate']), term(['lo', 'g'])),
  phrase(term(['per', 'sonal']), term(['pur', 'chase']))
];
